global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true

log:
  level: INFO
  format: json

ping:
  entryPoint: ping

accessLog:
  bufferingSize: 100
  format: json

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        options: default
  ping:
    address: :8080
  metrics:
    address: :9100

serversTransport:
  insecureSkipVerify: false

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
  docker:
    endpoint: tcp://docker-socket-proxy:2375
    exposedByDefault: false
    network: edge

certificatesResolvers:
  le-dns:
    acme:
      email: admin@inlock.ai
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
  le-tls:
    acme:
      email: admin@inlock.ai
      storage: /etc/traefik/acme/acme.json
      tlsChallenge: {}

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
