http:
  middlewares:
    admin-ip-allowlist:
      ipWhiteList:
        sourceRange:
          - "100.64.0.0/10"      # Tailscale (tailnet range)
          - "100.96.110.8/32"    # Tailscale client (MacBook)
          - "100.83.222.69/32"   # Tailscale server
          - "172.18.0.0/16"      # Docker mgmt network
          - "172.20.0.0/16"      # Docker edge network
