route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-admin'

receivers:
  - name: 'email-admin'
    email_configs:
      - to: 'admin@inlock.ai'
        from: 'alerts@inlock.ai'
        smarthost: 'mailu-front:587'
        auth_username: 'admin@inlock.ai'
        auth_password: '{{ .Secrets.email_password }}' # Placeholder, needs secret handling
        require_tls: true
