route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-admin'

receivers:
  - name: 'email-admin'
    email_configs:
      - to: 'admin@inlock.ai'
        from: 'alerts@inlock.ai'
        smarthost: 'mailu-postfix:25' # Internal mailu connection
        require_tls: false
